//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 02:12:58 PM BST 
//


package com.apakgroup.training.tutorial.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.apakgroup.training.tutorial.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.apakgroup.training.tutorial.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PriceRecordWire }
     * 
     */
    public PriceRecordWire createPriceRecordWire() {
        return new PriceRecordWire();
    }

    /**
     * Create an instance of {@link ValueVehicleResponse }
     * 
     */
    public ValueVehicleResponse createValueVehicleResponse() {
        return new ValueVehicleResponse();
    }

    /**
     * Create an instance of {@link GetPriceRecordByLookupCodeRequest }
     * 
     */
    public GetPriceRecordByLookupCodeRequest createGetPriceRecordByLookupCodeRequest() {
        return new GetPriceRecordByLookupCodeRequest();
    }

    /**
     * Create an instance of {@link DeletePriceRecordByIDResponse }
     * 
     */
    public DeletePriceRecordByIDResponse createDeletePriceRecordByIDResponse() {
        return new DeletePriceRecordByIDResponse();
    }

    /**
     * Create an instance of {@link AddPriceRecordResponse }
     * 
     */
    public AddPriceRecordResponse createAddPriceRecordResponse() {
        return new AddPriceRecordResponse();
    }

    /**
     * Create an instance of {@link GetPriceBandsByIDRequest }
     * 
     */
    public GetPriceBandsByIDRequest createGetPriceBandsByIDRequest() {
        return new GetPriceBandsByIDRequest();
    }

    /**
     * Create an instance of {@link ValueVehicleRequest }
     * 
     */
    public ValueVehicleRequest createValueVehicleRequest() {
        return new ValueVehicleRequest();
    }

    /**
     * Create an instance of {@link GetAllPriceRecordsResponse }
     * 
     */
    public GetAllPriceRecordsResponse createGetAllPriceRecordsResponse() {
        return new GetAllPriceRecordsResponse();
    }

    /**
     * Create an instance of {@link GetPriceBandsByIDResponse }
     * 
     */
    public GetPriceBandsByIDResponse createGetPriceBandsByIDResponse() {
        return new GetPriceBandsByIDResponse();
    }

    /**
     * Create an instance of {@link PriceBandWire }
     * 
     */
    public PriceBandWire createPriceBandWire() {
        return new PriceBandWire();
    }

    /**
     * Create an instance of {@link DeletePriceBandByIDResponse }
     * 
     */
    public DeletePriceBandByIDResponse createDeletePriceBandByIDResponse() {
        return new DeletePriceBandByIDResponse();
    }

    /**
     * Create an instance of {@link DeletePriceBandByLookUpCodeResponse }
     * 
     */
    public DeletePriceBandByLookUpCodeResponse createDeletePriceBandByLookUpCodeResponse() {
        return new DeletePriceBandByLookUpCodeResponse();
    }

    /**
     * Create an instance of {@link GetPriceRecordByLookupCodeResponse }
     * 
     */
    public GetPriceRecordByLookupCodeResponse createGetPriceRecordByLookupCodeResponse() {
        return new GetPriceRecordByLookupCodeResponse();
    }

    /**
     * Create an instance of {@link GetPriceRecordByIDRequest }
     * 
     */
    public GetPriceRecordByIDRequest createGetPriceRecordByIDRequest() {
        return new GetPriceRecordByIDRequest();
    }

    /**
     * Create an instance of {@link AddPriceBandResponse }
     * 
     */
    public AddPriceBandResponse createAddPriceBandResponse() {
        return new AddPriceBandResponse();
    }

    /**
     * Create an instance of {@link GetPriceRecordByIDResponse }
     * 
     */
    public GetPriceRecordByIDResponse createGetPriceRecordByIDResponse() {
        return new GetPriceRecordByIDResponse();
    }

    /**
     * Create an instance of {@link DeletePriceRecordByIDRequest }
     * 
     */
    public DeletePriceRecordByIDRequest createDeletePriceRecordByIDRequest() {
        return new DeletePriceRecordByIDRequest();
    }

    /**
     * Create an instance of {@link DeletePriceBandByIDRequest }
     * 
     */
    public DeletePriceBandByIDRequest createDeletePriceBandByIDRequest() {
        return new DeletePriceBandByIDRequest();
    }

    /**
     * Create an instance of {@link DeletePriceRecordByLookUpCodeRequest }
     * 
     */
    public DeletePriceRecordByLookUpCodeRequest createDeletePriceRecordByLookUpCodeRequest() {
        return new DeletePriceRecordByLookUpCodeRequest();
    }

    /**
     * Create an instance of {@link DeletePriceBandByLookUpCodeRequest }
     * 
     */
    public DeletePriceBandByLookUpCodeRequest createDeletePriceBandByLookUpCodeRequest() {
        return new DeletePriceBandByLookUpCodeRequest();
    }

    /**
     * Create an instance of {@link GetAllPriceRecordsRequest }
     * 
     */
    public GetAllPriceRecordsRequest createGetAllPriceRecordsRequest() {
        return new GetAllPriceRecordsRequest();
    }

    /**
     * Create an instance of {@link DeletePriceRecordByLookUpCodeResponse }
     * 
     */
    public DeletePriceRecordByLookUpCodeResponse createDeletePriceRecordByLookUpCodeResponse() {
        return new DeletePriceRecordByLookUpCodeResponse();
    }

    /**
     * Create an instance of {@link AddPriceBandRequest }
     * 
     */
    public AddPriceBandRequest createAddPriceBandRequest() {
        return new AddPriceBandRequest();
    }

    /**
     * Create an instance of {@link AddPriceRecordRequest }
     * 
     */
    public AddPriceRecordRequest createAddPriceRecordRequest() {
        return new AddPriceRecordRequest();
    }

    /**
     * Create an instance of {@link GetPriceBandsByLookUpCodeRequest }
     * 
     */
    public GetPriceBandsByLookUpCodeRequest createGetPriceBandsByLookUpCodeRequest() {
        return new GetPriceBandsByLookUpCodeRequest();
    }

    /**
     * Create an instance of {@link GetPriceBandsByLookUpCodeResponse }
     * 
     */
    public GetPriceBandsByLookUpCodeResponse createGetPriceBandsByLookUpCodeResponse() {
        return new GetPriceBandsByLookUpCodeResponse();
    }

    /**
     * Create an instance of {@link VehicleWire }
     * 
     */
    public VehicleWire createVehicleWire() {
        return new VehicleWire();
    }

    /**
     * Create an instance of {@link PriceRecordListWire }
     * 
     */
    public PriceRecordListWire createPriceRecordListWire() {
        return new PriceRecordListWire();
    }

    /**
     * Create an instance of {@link PriceRecordWire.PriceBands }
     * 
     */
    public PriceRecordWire.PriceBands createPriceRecordWirePriceBands() {
        return new PriceRecordWire.PriceBands();
    }

}
