//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.06 at 02:16:37 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.apakgroup.training.tutorial.webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.apakgroup.training.tutorial.webservice;
