//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.06 at 10:52:09 AM BST 
//


package com.apakgroup.training.tutorial.webservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriceRecordWire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceRecordWire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lookUpCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priceBands" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="priceBand" type="{com.apakgroup.training.tutorial.webservice}PriceBandWire" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceRecordWire", propOrder = {
    "lookUpCode",
    "priceBands"
})
public class PriceRecordWire {

    protected String lookUpCode;
    protected PriceRecordWire.PriceBands priceBands;

    /**
     * Gets the value of the lookUpCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLookUpCode() {
        return lookUpCode;
    }

    /**
     * Sets the value of the lookUpCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLookUpCode(String value) {
        this.lookUpCode = value;
    }

    /**
     * Gets the value of the priceBands property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRecordWire.PriceBands }
     *     
     */
    public PriceRecordWire.PriceBands getPriceBands() {
        return priceBands;
    }

    /**
     * Sets the value of the priceBands property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRecordWire.PriceBands }
     *     
     */
    public void setPriceBands(PriceRecordWire.PriceBands value) {
        this.priceBands = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="priceBand" type="{com.apakgroup.training.tutorial.webservice}PriceBandWire" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "priceBand"
    })
    public static class PriceBands {

        protected List<PriceBandWire> priceBand;

        /**
         * Gets the value of the priceBand property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the priceBand property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPriceBand().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PriceBandWire }
         * 
         * 
         */
        public List<PriceBandWire> getPriceBand() {
            if (priceBand == null) {
                priceBand = new ArrayList<PriceBandWire>();
            }
            return this.priceBand;
        }

    }

}
